gateways:
  local:
    connection:
      type: duckdb
      extensions:
        - mysql
      catalogs:
        memory: ':memory:'
        mysql_db:
          type: mysql
          path: {{ env_var('MYSQL_DUCKDB_PATH') }}


default_gateway: local

model_defaults:
  dialect: duckdb
