# All the variables in this file can be overridden, see https://sqlmesh.readthedocs.io/en/stable/guides/configuration/#overrides

gateways:
  local:
    connection:
      type: duckdb
      extensions:
        - mysql
      catalogs:
        memory: ':memory:'
        mysqldb:
          type: mysql
          path: {{ env_var('MYSQL_DUCKDB_PATH') }}

variables:
  output_db: sqlmesh
  output_table: consultations
  output_schema: mysqldb

default_gateway: local

model_defaults:
  dialect: duckdb
