apiVersion: batch/v1
kind: Job
metadata:
  name: harvest-job
spec:
  template:
    spec:
      containers:
      - name: harvest
        image: harvest-consultations
        command: ["uv", "run", "sqlmesh", "plan", "--auto-apply", "--run", "--verbose"]
        env:
        - name: SECRETS_YAML
          valueFrom:
            secretKeyRef:
              name: harvest
              key: SECRETS_YAML
      restartPolicy: Never
---
