apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: harvest-consultations
build:
  local:
    push: false
  artifacts:
  - image: harvest-consultations
    buildpacks:
      builder: "gcr.io/buildpacks/builder:google-22"
    sync:
      infer:
        - 'models'
manifests:
  hooks:
    before:
      - host:
          command: ["bash", "-c", 'kubectl create secret generic harvest --from-literal=SECRETS_YAML="$SECRETS_YAML" || echo "secret exists"']
  rawYaml:
      - k8s-*.yaml