apiVersion: v1
kind: Service
metadata: {name: adminer-service, namespace: harvest-consultations}
spec:
  selector:
    app: adminer
  ports: [{port: 80, targetPort: 80}]
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: adminer, namespace: harvest-consultations}
spec:
  replicas: 1
  selector: {matchLabels: {app: adminer}}
  template:
    metadata: {labels: {app: adminer}}
    spec:
      containers:
        - name: adminer
          image: dockette/adminer:dg
          ports: [{containerPort: 80}]
