name: SQLMesh Hourly
run-name: 🚀 SQLMesh Hourly 🚀
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  sqlmesh:
    name: SQLMesh Actions Workflow
    runs-on: training
    container:
      # Runner docker image
      image: ubuntu:24.04
    steps:
      - name: Install SQLite dependencies
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-0 libsqlite3-dev
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/checkout@v4
      - name: Install SQLMesh + Dependencies
        run: pip install -r requirements.txt
        shell: bash
      - name: Build and deploy sqlmesh prod env
        env:
          SECRETS_YAML: ${{ secrets.SECRETS_YAML }}
        run: sqlmesh plan --auto-apply --run --verbose
        shell: bash